/*
 * حق نشر 1390-1402 دانش پژوهان ققنوس
 * حقوق این اثر محفوظ است.
 *
 * استفاده مجدد از متن و یا نتایج این اثر در هر شکل غیر قانونی است مگر اینکه متن حق
 * نشر بالا در ابتدای تمامی مستندهای و یا برنامه‌های به دست آمده از این اثر
 * بازنویسی شود. این کار باید برای تمامی مستندها، متنهای تبلیغاتی برنامه‌های
 * کاربردی و سایر مواردی که از این اثر به دست می‌آید مندرج شده و در قسمت تقدیر از
 * صاحب این اثر نام برده شود.
 *
 * نام گروه دانش پژوهان ققنوس ممکن است در محصولات دست آمده شده از این اثر درج
 * نشود که در این حالت با مطالبی که در بالا اورده شده در تضاد نیست. برای اطلاع
 * بیشتر در مورد حق نشر آدرس زیر مراجعه کنید:
 *
 * http://dpq.co.ir/licence
 */


/**
 * \brief exception explanation
 *
 * \exception Exp1 Exception should be discussed here.
 * \exception Exp2 Exception should be discussed here.
 * \exception Exp3 Exception should be discussed here.
 *
 * This section causes new exception section to be generated by Doxygen.
 *
 * \exception Exp4 Exception should be discussed here.
 * \exception Exp5 Exception should be discussed here.
 */
int excetpion(Param p1, Param p2);
